Add string utilities
eclipse-velocitas/velocitas-lib pull request #14
Opened 2024-06-12 13:52 UTC by Chrylo

The additional string util methods "replace_text_area" and "replace_line" are helpful for text manipulation and auto generating code e.g. in the devenv-devcontainer-[setup](https://github.com/eclipse-velocitas/devenv-devcontainer-setup).

- I created a text_helper.py file for these and extracted other string manipulation methods from the init.py to here.
- A VS code config for easily executing and debugging the pytests was missing, so I added one.

2024-06-12 13:53 UTC, Chrylo commented on velocitas_lib/text_helper.py
Maybe rename to string_helper?

2024-06-12 15:03 UTC, dennismeister93 requested changes

2024-06-12 15:03 UTC, dennismeister93 commented on velocitas_lib/text_helper.py
> +                if replacement == "":
you dont need to check for an empty string here

python in general returns false when there is an empty string

In general it would be enough to do:

                if replacement:
                    buffer.append(replacement)

2024-06-13 07:52 UTC, Chrylo commented on velocitas_lib/text_helper.py
> +                replacement = line.replace(line, replacement)
Does not work. The line itself is not being changed inside the replace method. The new replaced string is only returned.

2024-06-13 07:56 UTC, dennismeister93 commented on velocitas_lib/text_helper.py
> +                replacement = line.replace(line, replacement)
I didn't check with other examples like the ones in the test, but this was working for me:

```
    buffer = []
    is_capturing = False
    for line in text:
        if not is_capturing and start_occurence in line:
            is_capturing = True
            continue

        if is_capturing:
            if end_occurence in line:
                is_capturing = False

                if replacement:
                    buffer.append(replacement)
        else:
            buffer.append(line)

    return buffer
```

2024-06-13 07:57 UTC, dennismeister93 commented on velocitas_lib/text_helper.py
i think text fits better. but i dont have a hard feeling about it :)

2024-06-13 07:58 UTC, Chrylo commented on velocitas_lib/text_helper.py
> +                if replacement == "":
Absolutely right :)

2024-06-13 11:45 UTC, dennismeister93 approved these changes
lgtm

2024-06-14 06:47 UTC, doosuu requested changes

2024-06-14 06:47 UTC, doosuu commented on tests/test_text_helper.py
> +test_text_literal: list[LiteralString] = """
`str` typing not sufficient here?

2024-06-14 06:47 UTC, doosuu commented on velocitas_lib/text_helper.py
Why not call this text_utils rather than text_helper?

2024-06-14 06:47 UTC, doosuu commented on velocitas_lib/text_helper.py
> +def replace_in_file(file_path: str, text: str, replacement: str) -> None:
```suggestion
def replace_text_in_file(file_path: str, text: str, replacement: str) -> None:
```
?

2024-06-14 06:47 UTC, doosuu commented on velocitas_lib/text_helper.py
> +def replace_line(
This function is basically replace_in_file but for a local buffer of strings rather than a file. Code could be simplified to call replace_line from replace_in_file.

2024-06-14 06:47 UTC, doosuu commented on velocitas_lib/text_helper.py
> +    If replacement for a line is empty, the line will be removed.
Removal of lines is a side effect which is not obvious from the function name or the parameters. I would say we add a parameter `remove_empty: bool = False` to the signature

2024-06-14 08:01 UTC, Chrylo commented on velocitas_lib/text_helper.py
Thought the same but was aligning the naming to the "conan_helper". Happy to use any naming pattern you got in the project. :)

2024-06-14 08:08 UTC, Chrylo commented on velocitas_lib/text_helper.py
> +def replace_in_file(file_path: str, text: str, replacement: str) -> None:
Should we also rename the other methods then? Like replace_text_in_line? Or the other way around? Removing the redundant text information because it is clear like: capture_textfile_area -> capture_area?

2024-06-14 10:03 UTC, doosuu requested changes

2024-06-14 10:03 UTC, doosuu commented on velocitas_lib/text_helper.py
> +def replace_in_file(file_path: str, text: str, replacement: str) -> None:
Basically I am fine with anything that is easy to read and conveys what it is doing Maybe something like this? 

(if we omit `textfile` from `capture_textfile_area` is it really clear what it is doing?)

Suggestion:
`text_utils.replace_text_in_file(...)`
`text_utils.replace_item_in_list(...)`
`text_utils.capture_area_in_file(...)`

2024-06-14 10:57 UTC, Chrylo commented on tests/test_text_helper.py
> +test_text_literal: list[LiteralString] = """
It is automatically a LiteralString because of """ and list[LiteralString] can't be converted to list[str]. :/

2024-06-14 11:02 UTC, Chrylo commented on velocitas_lib/text_helper.py
> +def replace_in_file(file_path: str, text: str, replacement: str) -> None:
The `textfile` methods should probably be in a utils class for `textfiles`. Then the context would be clear.

2024-06-14 20:48 UTC, doosuu requested changes

2024-06-14 20:48 UTC, doosuu commented on tests/test_text_utils.py
> +    # Remove empty lines
Put each test case for replace_item_in_list into a separate function.
Also applies to tests for other functions below.

2024-06-14 20:48 UTC, doosuu commented on tests/test_text_utils.py
> +def test_replace_line():
Function under test changed its name

2024-06-18 07:40 UTC, doosuu requested changes

2024-06-18 07:40 UTC, doosuu commented on tests/test_text_utils.py
> +    assert len(replaced_text) == 10
missing trailing whitespace

2024-06-18 07:40 UTC, doosuu commented on tests/test_text_utils.py
> +def test_item_in_list():
```suggestion
def test_item_in_list__replaces_all_occurrences_of_item_with_replacement():
```

2024-06-18 07:40 UTC, doosuu commented on tests/test_text_utils.py
> +def test_item_in_list_removes_empty_lines():
```suggestion
def test_item_in_list__remove_empty_enabled__removes_empty_lines_if_replacement_empty():
```

2024-06-18 07:40 UTC, doosuu commented on tests/test_text_utils.py
> +def test_item_in_list_keep_empty_lines():
```suggestion
def test_item_in_list__remove_empty_disabled__keeps_empty_lines():
```

2024-06-18 07:40 UTC, doosuu commented on tests/test_text_utils.py
> +def test_replace_text_area():
```suggestion
def test_replace_text_area__replaces_all_text_in_area_with_replacement():
```

2024-06-18 07:40 UTC, doosuu commented on tests/test_text_utils.py
> +def test_replace_text_area_remove_lines():
```suggestion
def test_replace_text_area__no_replacement_given__removes_lines():
```

2024-06-18 07:40 UTC, doosuu commented on tests/test_text_utils.py
> +def test_item_in_list():
Usually we tried to follow the scheme: <function_under_test>__<preconditions/parameter_combinations>__<expected_result>
I gave some suggestions on how the tests could be named.

2024-06-18 08:23 UTC, Chrylo commented on tests/test_text_utils.py
> +def test_replace_text_area_remove_lines():
Thx for the suggestions

2024-06-18 09:00 UTC, merged