Add read_file and write_file
eclipse-velocitas/velocitas-lib pull request #23
Opened 2024-09-09 06:32 UTC by wba2hi

2024-09-09 07:07 UTC, Chrylo requested changes

2024-09-09 07:07 UTC, Chrylo commented on velocitas_lib/text_utils.py
> +def read_file(
Can we put these into a file_utils class and write some simple unit tests? Otherwise LGTM.

2024-09-10 05:34 UTC, Chrylo commented
LGTM

2024-09-10 05:34 UTC, Chrylo approved these changes

2024-09-10 07:46 UTC, BjoernAtBosch approved these changes
LGTM

2024-09-10 08:52 UTC, merged